name: CI

on:
  push:
    branches:
      - main

jobs:
  build-base:
    name: Build Homestead image
    runs-on: ubuntu-latest
    #strategy:
    #  matrix:
    #    image: ['base','go']
    #  max-parallel: 1
    #  fail-fast: true

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        run: bash images/build_all.sh