name: Build Homestead images

on:
  push:
    branches:
      - main

jobs:
  build-base-images:
    name: Build Homestead image (base)
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./images/base/
          push: true
          tags: ghcr.io/simse/homestead/base:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}

  build-language-images:
    name: Build Homestead image
    runs-on: ubuntu-latest
    needs: build-base-images
    strategy:
      matrix:
        image: ['go']
      max-parallel: 32
      fail-fast: true

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./images/${{ matrix.image }}/
          push: true
          tags: ghcr.io/simse/homestead/${{ matrix.image }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
